### PR TITLE
Add materials to navigate github user interface

### PR DESCRIPTION
**Pull request by fliepeltje**
Hi there!

I want to help a research team to use github as a shared space for their code and other non-sensitive files. As a part of this I want to have some material for them on how to navigate the github user interface and how it relates to their work. 

If possible, I'd like feedback on the document. I would like to elaborate this further with two more items (with screenshots and steps):

- [x] **team onboarding guide**: How to start a team under the Utrecht University organization, add members to your team, and have discussions. 
- [] ~~**repository and project board organization for researchers**: Strategies of organizing code and texts using repository issues and project boards~~ This is an advanced feature and will be added in the future. 

Ideally I would like to come and have a chat with someone from your team who is interested in thinking about this. I think it would be really neat if we could get more research teams to do their work using github and given the recent move to enterprise, I feel the timing is quite good to make an effort to onboard people to the tools that github offers. I think it also aligns well with the themes of FAIR and open science.

### CODE REVIEW

**Comment by J535D165** [comment]
Hi @fliepeltje, thanks for sharing, and sorry for the late response. I think the document is very nice and welcome. I'm happy to have a chat with you (together with @jelletreep). Shall we set something up?

**Comment by jelletreep** [comment]
Hi @fliepeltje, sorry for the late reply from my side as well, and thanks a lot for your efforts. Happy to provide feedback and include it later on! I will plan something to have a chat!

**Comment by fliepeltje** [comment]
@jelletreep @J535D165 
I think this is what I would like to add with this first PR and expand on it based on what I get back as feedback from Plant Biology; if you could review and/or merge it, that would be great!

**Review by jelletreep — CHANGES_REQUESTED** [review]
Hi @fliepeltje, Thank you for this PR! We are happy with the manuals about managing your team and the web interface. The github for researchers article is also nice but we are hesitant if this repository is the right place for it, we will merge it now, but after summer we will have discussions with our communication advisor to determine what the main aims will be of this repository and where we will put what so it may change later. Can you go over the feedback?

**Comment by fliepeltje** [comment]
I think in light of my more recent experiences I would like to revise some of this content, so I'll for sure take the comments you left into account and build on that. I think it would be nice to have a more in-depth getting-started ready for the new academic year, so I will try to find some time for this soon. 

In terms of merging content, I am in no rush with that at all. So if you need to go over about topics that do or do not fit, then take your time. We can cherry pick things that immediately make sense and move other less relevant stuff to a later timepoint. 

thanks for the review :)

**Comment by jelletreep** [comment]
OK, then I propose to first merge the two manuals (with minor changes) then!

Thanks for your input! We have plans to create some capacity in our team for (among other things) maintaining these documentation pages, and as said we will also discuss things with our communication advisor, however we will start after summer.

Let's keep in touch about improving the getting started materials, so there will not be too many parallel efforts (e.g. there is a nice [github desktop workshop](https://zenodo.org/record/7740061) developed by the Geo data team and we are planning to create a workshop via RDM support (unfortunately the materials are not on github :smile: ). We rather have very good materials that everyone will use and where we can link to, then a lot of distributed efforts.

**Comment by fliepeltje** [comment]
Hey!
This is not currently on the fore-ground for me, in big part because I thought I had closed this PR. :sweat_smile: 

I accepted the changes and have the committed into the PR; feel free to merge and update in whatever way you see fit :) 

The revision I would like to do is more related to problems I ended up running into when working with researchers and in light of that I think it would be great to have some very use-case oriented articles (e.g. `Step-by-step guide for setting up a repo under UU`) and ideally they should be accompanied with web-casts with commentary; I think that would do a better job of explaining and contextualizing the github interface and its features

**Review by jelletreep — APPROVED** [review]

**Comment by jelletreep** [comment]
Thank you for the changes! I will merge now, and add some links to the manuals in the main page.

Thanks for the suggestion for use case oriented articles, sounds very useful. We will also invest time in updating this repository the coming months

**Pull request merged**
